Improvements and some simple refactorings
JStalnac/SharpSpades pull request #4
Opened 2021-05-17 02:22 UTC by luizfernandonb

2021-05-17 17:57 UTC, JStalnac requested changes
Looking great, good point add the `Async` suffix to `SendMap` and `SendPlayers`.

General note: code that checks if a parameter is null should throw an `ArgumentNullException`, not a `NullReferenceException`

2021-05-17 17:57 UTC, JStalnac commented on SharpSpades/Utils/Throw.cs
>          }
I think it's a bit redundant having a method that throws a given exception if a given condition isn't met as it's what regular if-statements do and the code doesn't really become much cleaner with it.

Also having to initialize a new exception object every time you want to use the helper method is propably not very good.

2021-05-17 17:57 UTC, JStalnac commented on SharpSpades/Net/Client.cs
> +        public ValueTask Disconnect(DisconnectReason reason)
This should be `DisconnectAsync` as the result is awaitable.

2021-05-17 18:06 UTC, JStalnac commented
Our editors/IDEs seem to have different code style configurations. I'll push a .editorconfig file tomorrow to address that problem.

2021-05-17 18:21 UTC, luizfernandonb commented
> Our editors/IDEs seem to have different code style configurations. I'll push a .editorconfig file tomorrow to address that problem.

Ok

2021-05-19 15:41 UTC, JStalnac requested changes
Good, one last thing: could you add back the `IfNull(value, paramName)` and `IfNull(value)` helper methods that throw the `ArgumentNullException` with the default message and maybe have e. g. packets use those instead of having a custom message?

Thank you for your patience!

2021-05-19 15:43 UTC, JStalnac commented
I'll do the code style thing on my own, you don't have to worry about it. I've been busy so I haven't had time to set up the editorconfig.

2021-05-19 16:09 UTC, luizfernandonb commented
> Good, one last thing: could you add back the `IfNull(value, paramName)` and `IfNull(value)` helper methods that throw the `ArgumentNullException` with the default message and maybe have e. g. packets use those instead of having a custom message?
> 
> Thank you for your patience!

I didn't understand this: `and maybe have e. g. packets use those instead of having a custom message?`
Can you explain again?

2021-05-19 16:12 UTC, luizfernandonb commented
> > Good, one last thing: could you add back the `IfNull(value, paramName)` and `IfNull(value)` helper methods that throw the `ArgumentNullException` with the default message and maybe have e. g. packets use those instead of having a custom message?
> > Thank you for your patience!
> 
> I didn't understand this: `and maybe have e. g. packets use those instead of having a custom message?`
> Can you explain again?

As I understand it, are you talking about using a NuGet package to launch a personalized message when an exception is thrown? If so, unfortunately I don't have a package

2021-05-19 16:32 UTC, JStalnac commented
Sorry if I was a bit unclear. I'm talking about using the `IfNull(value, paramName)` method in place of `IfNull(value, paramName, message)` which takes a custom message from `StringUtils.GenerateNullExceptionMessage` because the default message for `ArgumentNullException` works fine and results in less code.

2021-05-19 16:33 UTC, JStalnac commented
> Sorry if I was a bit unclear. I'm talking about using the `IfNull(value, paramName)` method in place of `IfNull(value, paramName, message)` which takes a custom message from `StringUtils.GenerateNullExceptionMessage` because the default message for `ArgumentNullException` works fine and results in less code.

I don't know how to explain this shortly :)

2021-05-19 17:32 UTC, JStalnac approved these changes
Great! Looking good! Thank you for your time and patience!

2021-05-19 17:32 UTC, merged